apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-spread-hint
  labels:
    app: nginx-spread-hint
spec:
  replicas: 12
  selector:
    matchLabels:
      app: nginx-spread-hint
  template:
    metadata:
      labels:
        app: nginx-spread-hint
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx-spread-hint
      containers:
      - name: nginxspread
        image: public.ecr.aws/t8y7s3k5/nginx-large:latest
        ports:
        - containerPort: 80
