apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-internet
  labels:
    app: nginx-internet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-internet
  template:
    metadata:
      labels:
        app: nginx-internet
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx-internet
      containers:
      - name: nginxinternet
        image: public.ecr.aws/t8y7s3k5/nginx-large:latest
        ports:
        - containerPort: 80
